ios_target_version = '14.1'
platform :ios, ios_target_version

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'R.swift'
end


target 'NoteTaking' do
  shared_pods

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # force minimum target to mute xcode warnings that range of supported deployment target versions is 9.0 to 15.0.99.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_target_version
    end
  end
end